name: Depenency check for a given repository

on:
  workflow_dispatch:
    inputs:
      organisation:
        description: "Organisation"
        required: true
        default: "nexi-intra"
      repo:
        description: "Repo"
        required: true
        default: "koksmat-captain"
run-name: Documenting ${{ github.event.inputs.organisation }}/${{ github.event.inputs.repo }} triggered by @${{ github.actor }}
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      # Define environment variables here
      WORKDIR: ${{ github.workspace }}
      DOC_REPO: ${{  github.event.inputs.repo }}
      DOC_ORG: ${{  github.event.inputs.organisation }}
      GH_ORGANISATION_WIDE_READ_REPO: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update Documents
        run: pwsh ./scripts/dependency/run.ps1
        shell: pwsh
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi
      - name: Commit Changes
        if: env.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "koksmat-actions"
          git config user.email "actions@koksmat.com"
          git add .
          git commit -m "Automated update by Koksmat Actions"  # The [skip ci] can be used as an additional safeguard
          git push
      - name: Trigger Build Workflow
        if: env.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/on-push.yml/dispatches \
            -d '{"ref":"main","inputs":{"reason":"Triggered via curl"}}'
